# 1. Name of workflow
name: Code Quality Check

# 2. When this workflow running?
on:
  push:
    branches:
      - main # Run this robot every time there is a push to main branch

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

# 3. What kind of job should robot do?
jobs:
  lint-check:
    runs-on: ubuntu-latest # Run the robot on free virtual box(ubuntu) owned by github

    steps:
      # Step A: Download the code from Github repo to Virtual Computer Linux
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step B: Install runtime Bun on Virtual Linux
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Step C: Install all app depedencies
      - name: Install depedencies
        run: bun install

      # Step C-2: Generate Prisma Client
      - name: Generate Prisma Client
        run: bun x prisma generate

      # Step D: Run the linting command
      - name: Run lint checker
        run: bun run lint

      # Step E: Run Typescript type checker
      - name: Run type checker
        run: bun x tsc --noEmit

      # Step F: Run Unit & Integration Tests
      - name: Run unit & integration tests
        run: bun test src/

      # Step F-2: Run production build
      - name: Run build checker
        run: bun run build

      # Step G: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: bun x playwright install --with-deps

      # Step H: Run E2E Tests
      - name: Run Playwright tests
        run: bun x playwright test

      # -------------------CD--------------------

      # Step I: Install Vercel CLI globally on the github server
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

      - name: Deploy Project Aartifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
